name: Deploy to UAT

on:
  push:
    branches: [ uat ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: false

env:
  ENVIRONMENT: uat
  REGISTRY: ghcr.io
  IMAGE_NAME_FRONTEND: ${{ github.repository }}/frontend
  IMAGE_NAME_BACKEND: ${{ github.repository }}/backend

jobs:
  build-and-deploy-frontend:
    name: Build and Deploy Frontend (UAT)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.UAT_API_URL }}
          NODE_ENV: production
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=uat-
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # Deployment step (uncomment and configure for your deployment target)
      # - name: Deploy to UAT Environment
      #   run: |
      #     # Add deployment commands here (e.g., kubectl, ssh, etc.)
      #     echo "Deploying to UAT environment..."
      
      - name: Run smoke tests
        run: |
          echo "Running smoke tests against UAT environment..."
          # Add smoke test commands here
      
      - name: Notify deployment status
        if: always()
        run: |
          echo "Frontend deployment to UAT: ${{ job.status }}"
          echo "Image: ${{ steps.meta.outputs.tags }}"

  build-and-deploy-backend:
    name: Build and Deploy Backend (UAT)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      
      - name: Install dependencies
        working-directory: ./backend
        run: npm ci
      
      - name: Run tests
        working-directory: ./backend
        run: npm test
        env:
          MONGODB_URI: ${{ secrets.UAT_MONGODB_URI }}
          JWT_SECRET: ${{ secrets.UAT_JWT_SECRET }}
          NODE_ENV: test
      
      - name: Build application
        working-directory: ./backend
        run: npm run build
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=uat-
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # Deployment step (uncomment and configure for your deployment target)
      # - name: Deploy to UAT Environment
      #   run: |
      #     # Add deployment commands here (e.g., kubectl, ssh, etc.)
      #     echo "Deploying to UAT environment..."
      
      - name: Run smoke tests
        run: |
          echo "Running smoke tests against UAT environment..."
          # Add smoke test commands here
      
      - name: Notify deployment status
        if: always()
        run: |
          echo "Backend deployment to UAT: ${{ job.status }}"
          echo "Image: ${{ steps.meta.outputs.tags }}"

  notify-stakeholders:
    name: Notify Stakeholders
    runs-on: ubuntu-latest
    needs: [build-and-deploy-frontend, build-and-deploy-backend]
    if: always()
    
    steps:
      - name: Send notification
        run: |
          echo "UAT deployment completed"
          echo "Frontend status: ${{ needs.build-and-deploy-frontend.result }}"
          echo "Backend status: ${{ needs.build-and-deploy-backend.result }}"
          # Add notification service integration here (Slack, Teams, etc.)
